#
# This is the server logic of a Shiny web application. You can run the
# application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(robmed)
library(DT)
library(officer)
library(flextable)
library(xtable)


# Define server logic required to draw a histogram
shinyServer(function(input, output, session) {


      session$onSessionEnded(function() { stopApp() })
      vals <- reactiveValues()
      vals$script <- c(paste("# Script generated by robmedExtra on", Sys.Date()),
                       "", "# load package", 'library("robmed")')
      # A list of dataframes used from the existing environment
      vals$used_data <- c()


      # Reactive expression to get data in dataframe
      get_data <- reactive({
        if (input$datatype == "Existing data frame"){
            if (is.null(input$dfname)) {
              final_df <- data.frame()
            } else {
              final_df <- as.data.frame(get(input$dfname, .GlobalEnv))
            }
          } else if (input$datatype == "RData") {
            if (is.null(input$rdata_dfname)) {
              final_df <- data.frame()
            } else {
              final_df <- as.data.frame(get(input$rdata_dfname, envir = new_env))
            }
          }

        colnames(final_df) <- make.names(colnames(final_df), unique = TRUE)
        final_df
      })

      numeric_data <- reactive({
        df <- get_data()
        Filter(is.numeric, df)
      })

      observe({
        updateTextInput(session, inputId = "rng_version_ols",
                        value = input$rng_version_robust)
        RNGversion(input$rng_version_robust)
      })

      observe({
        updateTextInput(session, inputId = "rng_version_robust",
                        value = input$rng_version_ols)
        RNGversion(input$rng_version_ols)
      })


      formula <- reactive({
        req(input$Explanatory, input$Response, input$Mediators)

        explanatory <- paste(input$Explanatory, collapse = "+")

        # Choose parallel as default when no mediator type is chosen
        if (length(input$Mediators) == 1 || input$Modeltype == "" ) {
          model_type <- "parallel"
        } else {
          model_type <- input$Modeltype
        }

        mediators <- paste("m(", paste(input$Mediators, collapse = ","),
                           ', .model = "',model_type,'")', sep = '')

        controls <- ''
        if(length(input$Covariates) != 0){
          controls <- paste("+","covariates(",
                            paste(input$Covariates, collapse = ","), ")")
        }
        formula_string <- paste(input$Response, "~", mediators,
                                      "+", explanatory, controls)


        form_out <- as.formula(formula_string)
      })

      df_name <- reactive({
        name <- ifelse(input$datatype == "RData", input$rdata_dfname,
                        input$dfname)

        name
      })

      # Creates boot_test_mediation object
      robust_bootstrap_test <- eventReactive(input$runRobust,{
        if (length(input$Mediators) > 1) {
          validate(need(input$Modeltype,
          "Please select a type of mediation model in the MODEL tab."))
        }

        vals$script <- c(vals$script, "",
                         "# Perform robust bootstrap test ROBMED")

      df_name <- ifelse(input$datatype == "RData", input$rdata_dfname,
                        input$dfname)

      # takes care of entering the data in the script
      if(input$datatype == "Existing data frame") {
        vals$used_data <- c(vals$used_data,
                            paste0(df_name,"(",
                                   paste(dim(get_data()), collapse = ","),
                                   ")"))
      } else {
        vals$script <- c(vals$script, paste0("load(",input$rdatafile$name, ")"))
      }

      command_control <- call("reg_control", efficiency = input$MM_eff,
                              max_iterations = input$max_iter)

      command_robust_test <- call("test_mediation",
                                  as.name(df_name),
                                  x = input$Explanatory,
                                  y = input$Response,
                                  m = input$Mediators,
                                  robust = TRUE,
                                  level = input$ConfidenceOLS,
                                  R = input$boot_samplesROBMED,
                                  control = as.name("ctrl")
                                  )

      command_seed <- call("set.seed", input$seedROBMED)


      if (!is.null(input$Covariates)) {
        command_robust_test$covariates <- input$Covariates
      }

      if (!is.null(input$Modeltype)) {
        command_robust_test$model <- input$Modeltype
      }

      if (!is.na(input$seedROBMED)) {
        eval(command_seed)
        vals$script <- c(vals$script, as.character(as.expression(command_seed)))
      }

      command_complete <- call("<-", as.name("robust_boot"), command_robust_test)
      command_control_complete <- call("<-",
                                       as.name("ctrl"),
                                       command_control)

      vals$script <- c(vals$script,
                       as.character(as.expression(command_control_complete)),
                       as.character(as.expression(command_complete)),
                       "summary(robust_boot)")

      eval(command_control_complete)
      eval(command_complete)
      })

      ols_bootstrap_test <- eventReactive(input$runOLS, {
        if (length(input$Mediators) > 1) {
          validate(need(input$Modeltype,
                        "Please select a type of mediation model in the MODEL tab."))
         }

         vals$script <- c(vals$script, "", "# Perform OLS bootstrap test")

         df_name <- ifelse(input$datatype == "RData", input$rdata_dfname,
                           input$dfname)

         # takes care of entering the data in the script
         if(input$datatype == "Existing data frame") {
           vals$used_data <- c(vals$used_data,
                               paste0(df_name,"(",
                                     paste(dim(get_data()), collapse = ","),
                                     ")"))


         } else {

           vals$script <- c(vals$script, paste0("load(",df_name, ")"))
         }

         command_seed <- call("set.seed", input$seedOLS)
         command_ols_test <- call("test_mediation",
                                  as.name(df_name),
                                  x = input$Explanatory,
                                  y = input$Response,
                                  m = input$Mediators,
                                  robust = FALSE,
                                  level = input$ConfidenceOLS,
                                  R = input$boot_samplesOLS)

         if (!is.null(input$Covariates)) {
           command_robust_test$covariates <- input$Covariates
         }

         if (!is.null(input$Modeltype)) {
           command_ols_test$model <- input$Modeltype
         }

         if (!is.na(input$seedOLS)) {
           eval(command_seed)
           vals$script <- c(vals$script,
                            as.character(as.expression(command_seed)))
         }

         command_complete <- call("<-", as.name("ols_boot"), command_ols_test)

         vals$script <- c(vals$script,
                                as.character(as.expression(command_complete)),
                          "summary(ols_boot)")

         eval(command_complete)
       })

      # Renders plot of expected vs empirical weights
      create_plot <- reactive({
          robust_boot_simple <- robust_bootstrap_test()
          summary_simple <- summary(robust_boot_simple)
          summary_simple$plot
      })

      output$plot_weights <- renderPlot({create_plot()})

      output$downloadPlot <- downloadHandler(
        filename = function() {
          if (input$plot_format == "png") {
            ext <- "png"
          } else if (input$plot_format == "pdf") {
            ext <- "pdf"
          }
          paste(Sys.Date(),"_",df_name(),"_","diagnostic_plot.", ext, sep = '')
        },
        content = function(file) {
          showModal(modalDialog("Loading", footer = NULL))
          on.exit(removeModal())

          if (input$plot_format == "png") {
            png(file, width = input$width_plot, height = input$height_plot,
                units = input$plot_units, res = input$plot_resolution)
          } else if (input$plot_format == "pdf") {
            if (input$plot_units == "cm") {
              # Convert to inch for pdf
              pdf(file, width = input$width_plot/2.54,
                  height = input$height_plot/2.54)
            } else if (input$plot_units == 'in') {
              pdf(file, width = input$width_plot, height = input$height_plot)
            }
          }
          print(create_plot())
          dev.off()
        },
        contentType = "image/png"
      )

    # Renders the summary text for ROBMED
    output$summary <- renderPrint({
      robust_boot_simple <- robust_bootstrap_test()
      summary(robust_boot_simple)
      })

    # Renders the summary text for OLS bootstrap
    output$summaryOLS <- renderPrint({
      robust_boot_simple <- ols_bootstrap_test()
      summary(robust_boot_simple)
    })

    observe({
      isolate(selectedInput <- input$Explanatory)
      updateSelectInput(session, inputId = "Explanatory",
                        choices = setdiff(colnames(get_data()),
                                          c(input$Mediators,
                                            input$Response,
                                            input$Covariates)),
                        selected = selectedInput)

    })

    observe({
      isolate(selectedInput <- input$Mediators)

      updateSelectInput(session, inputId = "Mediators",
                        choices = setdiff(colnames(numeric_data()),
                                          c(input$Explanatory,
                                            input$Response,
                                            input$Covariates)),
                        selected = selectedInput)
    })

    observe({
      isolate(selectedInput <- input$Response)
      updateSelectInput(session, inputId = "Response",
                        choices = setdiff(colnames(numeric_data()),
                                          c(input$Explanatory,
                                            input$Mediators,
                                            input$Covariates)),
                        selected = selectedInput)
    })

    observe({
      isolate(selectedInput <- input$Covariates)

      updateSelectInput(session, inputId = "Covariates",
                        choices = setdiff(colnames(get_data()),
                                          c(input$Explanatory,
                                            input$Response,
                                            input$Mediators)),
                        selected = selectedInput)
    })

    # Generates the UI that allows users to select variables of the data
    output$selectExplanatory <- renderUI({
      choices <- colnames(get_data())
      selectInput(inputId="Explanatory", label = "Independent variable(s)",
                  choices = choices, multiple = TRUE)
    })

    output$selectMediator <- renderUI({
      choices <- colnames(numeric_data())
      selectInput(inputId="Mediators",
                  label= p("Mediator(s)",
                           span("(Numeric)", style = "color: 	#A0A0A0")),
                  choices = choices, multiple = TRUE)
    })

    output$selectResponse <- renderUI({
      choices <- colnames(numeric_data())
      selectInput(inputId="Response",
                  label = p("Dependent variable",
                            span("(Numeric)", style = "color: 	#A0A0A0")),
                  choices = c("",choices), multiple = FALSE, selected = NULL)
    })

    output$selectControls <- renderUI({

      isolate(self <- input$Covariates)
      choices <- colnames(get_data())
      selectInput(inputId="Covariates",
                  label = p("Covariate(s)",
                            span("(Optional)", style = "color: 	#A0A0A0")),
                  choices = choices, multiple = TRUE)
    })

    # Creates input UI for type of data
    output$dataframechoice <- renderUI({

      if (input$datatype == "Existing data frame") {
        if (!any(as.logical(lapply(.GlobalEnv, is.data.frame)))){
          helpText("There are no data frames in your Global Environment.")
        } else {
          mydataframes <- names(which(unlist(eapply(.GlobalEnv,is.data.frame))))
          selectInput("dfname", "DataFrame from Global Env",
                      choices = mydataframes, multiple = FALSE)
        }
      }
      else if (input$datatype == "RData") {
        fileInput("rdatafile", "RData File",
                  accept = c(".RData"))
      }
    })

    # Creates input UI for the dataframe in an RData file
    output$rdatafile_dataframes <- renderUI({
      if (input$datatype == "RData") {
        req(input$rdatafile)
        new_env <<- new.env()
        load(input$rdatafile$datapath, new_env)

        dataframes <- names(which(unlist(eapply(new_env,is.data.frame))))

        selectInput("rdata_dfname", "DataFrame",
                    choices = dataframes)
      }
    })

    output$data_table <-  DT::renderDataTable({get_data()})

    output$robmedversion <- renderText({
      paste("ROBMED Package version: ", toString(packageVersion("robmed")))})

    output$downloadbuttonplot <- renderUI({
      req(input$runRobust)
      downloadButton("downloadPlot", "Download Plot")
    })

    output$downloadbuttonscript <- renderUI({
      req(input$runRobust)
      downloadButton("downloadScript", "Generate R script")
    })

    observeEvent(input$ConfidenceOLS, {
      updateSliderInput(session, "ConfidenceROBMED",
                        value = input$ConfidenceOLS)
    })

    observeEvent(input$ConfidenceROBMED, {
      updateSliderInput(session, "ConfidenceOLS",
                        value = input$ConfidenceROBMED)
    })

    observe({
      updateNumericInput(session, "seedOLS", value = input$seedROBMED)
      })

    observe({
      updateNumericInput(session, "seedROBMED", value = input$seedOLS)
    })

    output$downloadScript <- downloadHandler(

      filename = function() {
        paste(Sys.Date(), df_name(), "script.R", sep = "_")
      },
      content = function(file) {
        file.create(file)
        output_data <- paste("# Add the used datasets from the environment:",
                             paste(unique(vals$used_data), collapse = ", "))

        writeLines(c(output_data,vals$script), file)
      }
    )

    output$downloadbuttontableRobust <- renderUI({
      downloadButton("downloadTableRobust", "Download Table ROBMED")
    })

    output$downloadTableRobust <- downloadHandler(
      filename = function() {
        paste(Sys.Date(), df_name(), "table.docx", sep = "_")
      },
      content = function(file) {
        showModal(modalDialog("Loading table", footer=NULL))
        on.exit(removeModal())

        tabledoc <- export_table_MSWord(robust_bootstrap_test())
        print(tabledoc, file)
      }
    )

    output$downloadbuttontableOLS <- renderUI({
      downloadButton("downloadTableOLS", "Download Table OLS")
    })

    output$downloadTableOLS <- downloadHandler(
      filename = function() {
        paste(Sys.Date(), df_name(), "table.docx", sep = "_")
      },
      content = function(file) {
        showModal(modalDialog("Loading table", footer=NULL))
        on.exit(removeModal())

        tabledoc <- export_table_MSWord(ols_bootstrap_test())
        print(tabledoc, file)
      }
    )

    output$ui_model_type <- renderUI({
      if (length(input$Mediators) > 1) {
      selectInput("Modeltype", "Multiple mediator model:",
                  choices = c("", 'parallel', 'serial'), selected = NULL)
      }
    })

    output$ui_runbutton_robmed <- renderUI({
      req(input$Mediators, input$Response, input$Explanatory)
      actionButton("runRobust", "Run")
    })

    output$ui_runbutton_ols <- renderUI({
      req(input$Mediators, input$Response, input$Explanatory)
      actionButton('runOLS', 'Run')
    })


    observeEvent(input$plot_units, {
      if (input$plot_units == "in") {
        min_val <- 1
        max_val <- 40
        standard <- 7
      } else if (input$plot_units == "cm") {
        min_val <- 2.54
        max_val <- 101.6
        standard <- 17.78
      }

      updateSliderInput(session, inputId = "width_plot",
                        label = "Width plot",
                        min = min_val, max = max_val, value = standard)
      updateSliderInput(session, inputId = "height_plot",
                        label = "Height plot",
                        min = min_val, max = max_val, value = standard)
    })

    output$download_tables <- downloadHandler(
      filename = function() {
        paste0(Sys.Date(), "_", df_name(), "_", "table", "_",input$table_orientation, ".docx")
      },
      content = function(file) {
        showModal(modalDialog("Loading", footer = NULL))
        on.exit(removeModal())

        mediation_list <- list()

        if (isTruthy(input$models_tables)) {
          contains_robust <- "ROBMED" %in% input$models_tables
          contains_ols <- "OLS" %in% input$models_tables
        } else {
          contains_robust <- TRUE
          contains_ols <- TRUE
        }

        if (contains_robust) {
          if(isTruthy(input$runRobust)) {
            mediation_list$robust <- robust_bootstrap_test()
          }
        }

        if (contains_ols) {
          if(isTruthy(input$runOLS)) {
            mediation_list$ols <- ols_bootstrap_test()
          }
        }

        document <- export_table_MSWord(mediation_list,
                                        orientation = input$table_orientation)
        print(document, file)
      }
    )

    output$ui_checkbox_table <- renderUI({
      if (isTruthy(robust_bootstrap_test()) && isTruthy(ols_bootstrap_test())) {
        checkboxGroupInput(inputId = "models_tables",
                           label = "Models to include:",
                           choices = c("ROBMED", "OLS"),
                           selected = c("ROBMED", "OLS"))
      }
    })

    output$ui_resolution <- renderUI({
      if (input$plot_format == "png") {
        numericInput(inputId = "plot_resolution",
                     label = "Resolution of the plot (ppi)",
                     value = 300)
      }

    })


#' Export result table to Word
#'
#' Export the table containing results of mediation analysis to a Microsoft Word
#' document.
#'
#' @param test_model an object inheriting from class
#' \code{"\link{test_mediation}"} or a list of objects of that class.
#' of object
#'
#' @param digits a positive integer, which determines the number of decimals
#' that should be displayed in the table. The default is to display 4 decimals.
#'
#' @param orientation the  orientation in which the table is displayed in the
#' document. When set to portrait, the tables are displayed
#' underneath each other. When set to landscape, the tables are displayed side
#' by side.
#'
#'
#' @return An object of class \code{"\link{rdocx}"}, containing a table of the
#' results of the provided objects.
#'
#'
#' @author Vincent Drenth
#'
#'
#' @examples
#' data("BSG2014")
#'
#' boot_simple <- test_mediation(TeamCommitment ~
#'                                 m(TaskConflict) +
#'                                   ValueDiversity,
#'                               data = BSG2014)
#'
#' table <- export_table_MSWord(boot_simple)
#' print(table, target = "filename.docx")
#'
#' @export

export_table_MSWord <- function(test_model, ...) {
  UseMethod("export_table_MSWord")
}

# Takes two flextables and merges them into 1, expanding over columns
merged_flextable <- function(test1, test2) {
  ft1 <- to_flextable(test1)
  ft2 <- to_flextable(test2)

  merged_df <- data.frame(ft1$body$dataset, ft2$body$dataset[,-1],
                          check.names = FALSE)

  # Work around to prevent duplicate col keys
  for(i in c(6:9)) {
    colnames(merged_df)[i] <- paste0(colnames(merged_df)[i], "\r")
  }
  merged_ft <- flextable(merged_df)

  start_merge <- which(merged_df[,1] == "Indirect Effects")

  indirect_range <- c(start_merge : nrow(ft1$body$dataset))

  for (index in indirect_range) {
    merged_ft <- merge_at(merged_ft, i = index, j = 3:4)
    merged_ft <- merge_at(merged_ft, i = index, j = 7:8)
  }

  merged_ft <- autofit(merged_ft)
  merged_ft <- flextable::align(merged_ft, align = "center", part = "all")

  # Changing cosmetics
  merged_ft <- theme_booktabs(merged_ft, bold_header = TRUE)
  merged_ft <- bold(merged_ft, i = start_merge, bold = TRUE)

  merged_ft <- add_header_row(merged_ft,
                              top = TRUE,
                              values = c("",get_method_robmed(test1),
                                         get_method_robmed(test2)),
                       colwidths = c(1,4,4))

  footer_text_left <- paste('Sample size = ', nrow(test1$fit$data),
                       '. Number of bootstrap samples = ', test1$R , ".\n",
                       "†p < .1. *p < .05. **p < .01. ***p < .001.")

  footer_text_right <- paste('Sample size = ', nrow(test2$fit$data),
                            '. Number of bootstrap samples = ', test2$R , ".\n",
                            "†p < .1. *p < .05. **p < .01. ***p < .001.")

  merged_ft <- add_footer_row(merged_ft,
                              values = c(footer_text_left, footer_text_right),
                              colwidths = c(4, 5))

  merged_ft <- hline(merged_ft, border = NULL, part = "body")

  return(merged_ft)
}

#' @export
#'
export_table_MSWord.list <- function(test_model,
                                     orientation = c("landscape", "portrait"),
                                     filename = NULL,
                                     ...) {
  doc <- officer::read_docx()

  if (orientation == "landscape") {
    tables <- to_flextable(test_model = test_model, digits = digits,
                            merged = TRUE)
    doc <- officer::body_end_section_landscape(doc)

    for(table in tables) {
      doc <- flextable::body_add_flextable(doc, table)
    }
    doc <- officer::body_end_section_landscape(doc)

  } else if (orientation == "portrait") {
      count_page <- 0
      tables <- to_flextable(test_model = test_model, digits = digits,
                              merged = FALSE)

      for (table in tables) {
        doc <- flextable::body_add_flextable(doc, table)
        doc <- body_add_par(doc, value = "")

        count_page <- count_page + 1

        if (count_page %% 2 == 0) {
        doc <- officer::body_add_break(doc, "after")
        }
      }
  }


  if (!is.null(filename)) {
    print(doc, filename)
  } else {
    return(doc)
  }
}

#'@export
export_table_MSWord.test_mediation <- function(test_model,
                                               digits = 4,
                                               filename = NULL,
                                               ...) {
  table <- to_flextable(test_model = test_model, digits = digits)

  doc <- read_docx()
  doc <- body_add_flextable(doc, table)
  if (!is.null(filename)) {
    print(doc, filename)
  } else {
    return(doc)
  }
}

# Function using xtable to create latex table
to_latex <- function(test_model, digits = 4) {
  table <- to_flextable(test_model = test_model, digits = digits)
  dataset <- table$body$data
  indirect_start <- which(dataset[,1] == "Indirect Effects")


  full_table <- xtable(dataset, align = "llcccc")
  final_table_character <- print(full_table, booktabs = T, hline.after = (-1:nrow(dataset)),
        include.rownames = F, type = "latex")

  final_table_character <- gsub(pattern = "(\\(-[^)]*\\))",
                                replacement = paste0("\\\\multicolumn{2}{c}{",
                                                     "\\1", "}"),
                                x = final_table_character)

  final_table_character <- gsub(pattern = "(Confidence Interval &  )",
                                replacement = "\\\\multicolumn{2}{c}{Confidence Interval}",
                                x = final_table_character)

  final_table_character <- gsub(pattern = "&  &",
                                replacement = "&",
                                x = final_table_character)



  cat(final_table_character, sep = "\n")
}

# Works kind of but not so nice
merge_vertical_xtable <- function(table1, table2) {

  list_table1 <- table1
  list_table2 <- table2

  # Remove last line from first table and first 3 from second table
  list_table1 <- list_table1[1:(length(list_table1) - 1)]
  list_table2 <- list_table2[4:length(list_table2)]

  full_table <- append(list_table1, list_table2)
  return(full_table)
}


#' Create flextable from mediation test
#'
#' Creates a flextable from a test_mediation object
#'
#' @param test_model an object inheriting from class
#' \code{"\link{test_mediation}"} or a list of objects of that class.
#' of object
#'
#' @param digits a positive integer, which determines the number of decimals
#' that should be displayed in the table. The default is to display 4 decimals.
#'
#' @param merged boolean that determines whether the flextables are merged to show
#' the results of two tests in one table (except possibly the last one) or
#' seperate. Only used when test_model
#' is a list.
#'
#' @return An object of class \code{"\link{flextable}"} or a list of objects of
#' this class.
#'
#' @importFrom flextable theme_booktabs algin bold add_header_row autofit
#' merge_at flextable add_footer_row hline
#'
#' @author Vincent Drenth
#'
#' @examples
#' data("BSG2014")
#'
#' boot_robust <- test_mediation(TeamCommitment ~
#'                                 m(TaskConflict) +
#'                                   ValueDiversity,
#'                               data = BSG2014)
#'
#' ft <- to_flextable(boot_robust)
#'
#' boot_ols <- test_mediation(TeamCommitment ~
#'                                 m(TaskConflict) +
#'                                   ValueDiversity,
#'                               data = BSG2014,
#'                               robust = FALSE)
#'
#' flextables_list <- to_flextable(list(boot_robust, boot_ols))
#'
#'
#' @export

to_flextable <- function(test_model, ...) {
  UseMethod("to_flextable")
}


#' @export
#' @method to_flextable test_mediation

to_flextable.test_mediation <- function(test_model, digits = 4) {

  df_stacked <- prep_data_table(test_model = test_model, digits = digits)
  ft <- flextable(df_stacked)
  start_merge <- which(df_stacked[,1] == "Indirect Effects")

  # Merge the third and fourth column for the indirect effects to create one
  # column for the confidence interval
  indirect_range <- c(start_merge: (nrow(df_stacked)))

  for (index in indirect_range) {
    ft <- merge_at(ft, i = index, j = 3:4)
  }

  # Changing cosmetics
  ft <- flextable::theme_booktabs(ft, bold_header = TRUE)
  ft <- flextable::align(ft, align = "center", part = "all")
  ft <- bold(ft, i = start_merge, bold = T)
  ft <- add_header_row(ft, top = TRUE, values = c(get_method_robmed(test_model)),
                       colwidths = c(5))
  ft <- hline(ft, border = NULL, part = "body")

  for (row in c(1:(start_merge - 1))) {
    orig_text <- df_stacked[row,1]
    text_list <- strsplit(orig_text, " ")[[1]]

    effect <- paste(text_list[1:3], collapse = " ")
    letter_number <- strsplit(gsub("[()]", "", text_list[4]), "")[[1]]
    if (letter_number[2] == "'") {
      letter = paste0(letter_number[1:2], collapse = "")
      number = paste0(letter_number[3:length(letter_number)], collapse = "")
    } else {
      letter = letter_number[1]
      number = paste0(letter_number[2:length(letter_number)], collapse = "")
    }



    new_text <- as_paragraph(as_chunk(effect), as_chunk(" ("),
                             as_chunk(letter),
                             as_sub(number),
                             as_chunk(")"))

    ft <- flextable::compose(ft, i = row, j = 1, value = new_text)
  }

  ft <- autofit(ft)

  return(ft)
}

#' @export
#' @method to_flextable list
to_flextable.list <- function(test_model, digits, merged = F, ...) {
  result = list()
  count <-
  if(merged) {
    for (index in seq(1, ceiling((length(test_model) + 1)/2), 2)) {
      test_model_left <- test_model[[index]]
      test_model_right <- test_model[[index + 1]]

      ft <- merged_flextable(test_model_left, test_model_right)
      result <- append(result, list(ft))
    }

    if (length(test_model) %% 2 == 1) {
      ft <- to_flextable(test_model[[length(test_model)]])
      result <- append(result, list(ft))
    }

  } else {
    for(test in test_model) {
      ft <- to_flextable(test)
      result <- append(result, list(ft))
    }
  }

  return(result)
}

# Creates a single dataframe that contains the data needed to create the table
# The 4th column contains NA for all rows corresponding to the indirect effects
# as the 3rd and 4th column will be later merged to create the column for
# the Confidence Interval

prep_data_table <- function(test_model, digits = 4, p_values = T) {
  sm <- summary(test_model)$summary

  if (test_model$fit$model == "serial") {
    if (length(sm$m) == 1) {
      directrows <- 3 * (length(sm$x)) + 1
      indirectrows <- length(sm$x)

    } else if (length(sm$m) == 2) {
      # to generate table for 2 serial mediators
      directrows <- 4 * length(sm$x) + 3
      indirectrows <- 3 * length(sm$x)
    } else if (length(sm$m) == 3) {
      # Table for 3 serial mediators
      directrows <- 4 * length(sm$x) + 5 + 2
      indirectrows <- (3 + 3 + 1) * length(sm$x)
    }
  } else {
    #Model is parallel
    rows = 2 * (length(sm$x) * length(sm$m)) + 2 * length(sm$x) + length(sm$m)
    indirectrows = length(sm$x) * length(sm$m)
    directrows = rows - indirectrows
  }

  # Create dataframe for the direct effects
  df_dir <- data.frame(matrix(NA, nrow = directrows, ncol = 5))

  row <- 1
  for (med in sm$m) {
    if (length(sm$m) > 1){
      coefs_a <- sm$fit_mx[med][[1]]$coefficients
    } else {
      coefs_a <- sm$fit_mx$coefficients
    }

    #Add a paths
    for (reg in sm$x) {
      df_dir[row, 1] <- paste(reg,"->", med, paste0("(a", row, ")"))
      df_dir[row, 2:5] <- coefs_a[reg, 2:5]
      row <- row + 1
    }
  }
  a_paths <- row

  coefs_b <- sm$fit_ymx$coefficients
  for (med in sm$m) {
    #Add b paths
    df_dir[row, 1] <- paste(med ,"->" , sm$y,
                            paste0("(b", row - a_paths + 1, ")"))
    df_dir[row, 2:5] <- coefs_b[med, 2:5]
    row <- row + 1
  }
  b_paths <- row

  # Add c path (Direct effect)
  for (reg in sm$x){
    df_dir[row, 1] <- paste(reg,'->', sm$y,
                            paste0("(c", row - b_paths + 1, ")"))
    df_dir[row, 2:5] <- sm$direct[reg, 2:5]
    row <- row + 1
  }
  c_paths <- row

  # Add c' path (Total effect)
  for (reg in sm$x) {
    df_dir[row, 1] <- paste(reg, "->", sm$y,
                            paste0("(c'", row - c_paths + 1, ")"))
    df_dir[row, 2:5] <- sm$total[reg, 2:5]
    row <- row + 1
  }

  if (test_model$fit$model == "serial" && length(sm$m) > 1) {

    if (length(sm$m) == 2) {
    df_dir[row, 1] <- paste(paste(sm$m, collapse = "->"), "(d)")
    df_dir[row, 2:5] <- as.numeric(sm$fit_mx[sm$m[2]][[1]]$coefficients[sm$m[1],2:5])
    row <- row + 1

    } else if (length(sm$m) == 3) {
      d_paths <- names(test_model$d)

      for (path in d_paths) {
        meds <- strsplit(path, split = "->")[[1]]
        med1 <- meds[1]
        med2 <- meds[2]

        coefs <- sm$fit_mx[med2][[1]]$coefficients[med1, 2:5]
        df_dir[row, 1] <- paste(path, "(d)")
        df_dir[row, 2:5] <- as.numeric(coefs)
        row <- row + 1

      }
    }
  }

  if (p_values) {
    pvals <- p_value(test_model, parm = "indirect")
  }
  # changing number of columns from 4 to 5. Last column should contain p-vals
  # 4th column should be empty

  #Add indirect effects (a (d) b paths)
  df_ind <- data.frame(matrix(0, nrow = indirectrows, ncol = 4))

  if (test_model$fit$model == "serial" ){
    row <- 1
    for (reg in sm$x) {
        # The effectname in this case is "reg -> med_1 -> ... -> med_n" with
        # n for 1 up to 3. The order of mediators remains the same but can skip
        # a value.


      indirect_effects <- list()

      if (length(sm$m) >= 1) {
        indirect_effects <- append(indirect_effects, list(1))
      }
      if (length(sm$m) >= 2) {
        indirect_effects <- append(indirect_effects, list(c(2)))
        indirect_effects <- append(indirect_effects, list(c(1:2)))
      }
      if (length(sm$m) == 3) {
        indirect_effects <- append(indirect_effects, list(c(3)))
        indirect_effects <- append(indirect_effects, list(c(1,3)))
        indirect_effects <- append(indirect_effects, list(c(2:3)))
        indirect_effects <- append(indirect_effects, list(c(1:3)))
      }


      for (effect in indirect_effects) {
        effectname <- paste(reg, paste0(sm$m[effect], collapse = "->"), sep = "->")

        if (length(sm$x) == 1) {
          effectname <- gsub(pattern = paste0(reg,"->"),
                             replacement = "",
                             x = effectname)
        }

        x <<- effectname
        df_ind[row,1] <- paste(effectname, '(Indirect)')

        if (length(sm$m) > 1) {
            # TODO Add case of three mediators. This code is for only two.

            df_ind[row, 2] <- test_model$indirect[effectname][[1]]

            lower <- round(test_model$ci[effectname, 1], digits)
            upper <- round(test_model$ci[effectname, 2], digits)

        } else {
          df_ind[row,2] <- test_model$indirect[reg][[1]]


          lower <- round(test_model$ci[1], digits)
          upper <- round(test_model$ci[2], digits)
        }

        df_ind[row, 3] <- paste('(', lower, ',',upper,')', sep = '')
        df_ind[row, 4] <- pvals[paste("Indirect", effectname, sep = "_")][[1]]


        row <- row + 1
      }
    }

  } else {
    # Parallel model
    row <- 1
    for (reg in sm$x) {
      for (med in sm$m) {
        effectname <- paste(reg, "->", med, sep = "")
        df_ind[row,1] <- paste(effectname, "(Indirect)")

        if (length(sm$m) > 1) {
          if (length(sm$x) > 1) {
            lower <- round(test_model$ci[effectname, 1], digits)
            upper <- round(test_model$ci[effectname, 2], digits)
            df_ind[row, 2] <- test_model$indirect[effectname][[1]]
            df_ind[row, 4] <- pvals[paste("Indirect", effectname,
                                          sep = "_")][[1]]

          } else {
            # Only 1 explanatory variable, multiple mediators
            lower <- round(test_model$ci[med, 1], digits)
            upper <- round(test_model$ci[med, 2], digits)
            df_ind[row, 2] <- test_model$indirect[med][[1]]
            df_ind[row, 4] <- pvals[paste("Indirect", med, sep = "_")][[1]]

          }
        } else {
          # Only 1 mediator
          if (length(sm$x) > 1) {
            lower <- round(test_model$ci[reg, 1], digits)
            upper <- round(test_model$ci[reg, 2], digits)
            df_ind[row,2] <- test_model$indirect[reg][[1]]
            df_ind[row, 4] <- pvals[paste("Indirect", reg, sep = "_")][[1]]

          } else {
            # only 1 indirect effect
            df_ind[row,2] <- test_model$indirect
            lower <- round(test_model$ci[1], digits)
            upper <- round(test_model$ci[2], digits)
            df_ind[row, 4] <- pvals["Indirect"][[1]]

          }
        }
        df_ind[row, 3] <- paste("(", lower, ", ", upper,")", sep = "")
        row <- row + 1
      }
    }
  }

  # Create the table from the dataframes
  df_rounded <- data.frame(lapply(df_dir, function(y) if(is.numeric(y)) round(y, digits) else y))
  df_ind_rounded <- data.frame(lapply(df_ind, function(y) if(is.numeric(y)) round(y, digits) else y))

  colnames(df_ind_rounded) <- c("Indirect Effects", "Estimate",
                                "Confidence Interval", "p-value")

  colnames(df_rounded) <- c("Direct Effects", "Estimate", "Std. Error",
                            "z statistic", "p-value")

  dim_ind <- dim(df_ind_rounded)
  dim_dir <- dim(df_rounded)

  df_ind_merge <- as.data.frame(matrix(NA, nrow = dim_ind[1], ncol = dim_ind[2]))
  df_ind_merge[,1:3] <- df_ind_rounded[,1:3]
  df_ind_merge[,5] <- df_ind_rounded[,4]

  df_ind_merge <- rbind(c("Indirect Effects", "Estimate",
                          "Confidence Interval","", "p-value"), df_ind_merge)

  df_dir_merge <- df_rounded
  colnames(df_dir_merge) <- colnames(df_ind_merge)
  df_dir_merge <- data.frame(apply(df_dir_merge, FUN = as.character, MARGIN = 2))

  df_stacked <- rbind(df_dir_merge, df_ind_merge)
  colnames(df_stacked) <- c("Direct Effects", "Estimate", "Std. Error",
                            "z statistic", "p-value")
  return(df_stacked)
}


get_method_robmed <- function(test_model) {
  # TODO implement this function to return the proper method type for different
  # methods included in robmed based on robust, method, and family attributes
  if (test_model$fit$robust %in% c("MM", TRUE)) {
    return("ROBMED")
  } else {
    return("OLS Bootstrap")
  }

}
})
