\documentclass{article}

% % additional packages
\usepackage[a4paper]{geometry}


\begin{document}


% knitr options
<<setup, include=FALSE, cache=FALSE>>=
library("knitr")
opts_chunk$set(fig.path="figures/figure-", fig.align="center")
options(prompt="R> ", continue="+  ", width=72, useFancyQuotes=FALSE)
@


<<include=FALSE>>=
# load package and data
library("robmedExtra")
data("BSG2014")
# seed to be used for the random number generator
seed <- 20211117
@


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# compute mediation analysis
boot_simple <- test_mediation(BSG2014,
                              x = "ValueDiversity",
                              y = "TeamCommitment",
                              m = "TaskConflict")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_simple)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_serial <- test_mediation(BSG2014,
                              x = "ValueDiversity",
                              y = "TeamScore",
                              m = c("TaskConflict", "TeamCommitment"),
                              model = "serial")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a serial multiple mediator model, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_serial)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_multiple <- test_mediation(BSG2014,
                              x = c("SharedLeadership",
                                    "AgeDiversity",
                                    "GenderDiversity"),
                              y = "TeamPerformance",
                              m = "ProceduralJustice")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a model with multiple independent variables, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_multiple)
@
\end{table}


% ----------
% references
% ----------

% \bibliographystyle{plainnat}
% \bibliography{bibfile}   % name the BibTeX data base

\end{document}
