\documentclass{article}

% % additional packages
\usepackage[a4paper]{geometry}
\usepackage{rotating}  % for sidewaystable


\begin{document}


% knitr options
<<setup, include=FALSE, cache=FALSE>>=
library("knitr")
opts_chunk$set(fig.path="figures/figure-", fig.align="center")
options(prompt="R> ", continue="+  ", width=72, useFancyQuotes=FALSE)
@


<<include=FALSE>>=
# load package and data
library("robmedExtra")
data("BSG2014")
# seed to be used for the random number generator
seed <- 20211117
@


<<include=FALSE>>=
# apply OLS Sobel test
set.seed(seed)
ols_sobel <- test_mediation(BSG2014,
                            x = "ValueDiversity",
                            y = "TeamCommitment",
                            m = "TaskConflict",
                            test = "sobel",
                            method = "regression",
                            robust = FALSE)

# apply OLS bootstrap
set.seed(seed)
ols_boot <- test_mediation(BSG2014,
                           x = "ValueDiversity",
                           y = "TeamCommitment",
                           m = "TaskConflict",
                           test = "boot",
                           method = "regression",
                           robust = FALSE)

# apply winsorized bootstrap
set.seed(seed)
winsorized_boot <- test_mediation(BSG2014,
                                  x = "ValueDiversity",
                                  y = "TeamCommitment",
                                  m = "TaskConflict",
                                  test = "boot",
                                  method = "covariance",
                                  robust = TRUE)

# apply ROBMED
set.seed(seed)
robust_boot <- test_mediation(BSG2014,
                              x = "ValueDiversity",
                              y = "TeamCommitment",
                              m = "TaskConflict",
                              test = "boot",
                              method = "regression",
                              robust = TRUE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using various methods.}
<<echo=FALSE, results="asis">>=
boot_list <- list(ols_sobel, ols_boot, robust_boot)
to_latex(boot_list, orientation = "portrait")
@
\end{table}

\begin{sidewaystable}[h!]
\caption{Results from mediation analysis for a simple mediation model, using various methods.}
<<echo=FALSE, results="asis">>=
boot_list <- list(ols_sobel, ols_boot, winsorized_boot, robust_boot)
to_latex(boot_list, orientation = "landscape")
@
\end{sidewaystable}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_simple <- test_mediation(BSG2014,
                              x = "ValueDiversity",
                              y = "TeamCommitment",
                              m = "TaskConflict")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_simple)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_serial <- test_mediation(BSG2014,
                              x = "ValueDiversity",
                              y = "TeamScore",
                              m = c("TaskConflict", "TeamCommitment"),
                              model = "serial",
                              contrast = FALSE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a serial multiple mediator model, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_serial)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_parallel <- test_mediation(BSG2014,
                                x = "SharedLeadership",
                                y = "TeamPerformance",
                                m = c("ProceduralJustice",
                                      "InteractionalJustice"),
                                covariates = c("AgeDiversity",
                                               "GenderDiversity"),
                                contrast = FALSE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a parallel multiple mediator model, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_parallel)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_multiple <- test_mediation(BSG2014,
                              x = c("SharedLeadership",
                                    "AgeDiversity",
                                    "GenderDiversity"),
                              y = "TeamPerformance",
                              m = "ProceduralJustice",
                              contrast = FALSE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a model with multiple independent variables, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_multiple)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_mult_par <- test_mediation(BSG2014,
                              x = c("SharedLeadership",
                                    "AgeDiversity",
                                    "GenderDiversity"),
                              y = "TeamPerformance",
                              m = c("ProceduralJustice",
                                    "InteractionalJustice"),
                              contrast = FALSE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a parallel multiple mediator model with multiple independent variables, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_mult_par)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
boot_mult_ser <- test_mediation(BSG2014,
                                x = c("ValueDiversity", "AgeDiversity"),
                                y = "TeamScore",
                                m = c("TaskConflict", "TeamCommitment"),
                                model = "serial",
                                contrast = FALSE)
@

\begin{table}[h!]
\caption{Results from mediation analysis for a serial multiple mediator model with multiple independent variables, using the robust bootstrap test ROBMED.}
<<echo=FALSE, results="asis">>=
to_latex(boot_mult_ser)
@
\end{table}


<<include=FALSE>>=
# set seed of the random number generator
set.seed(seed)
# perform mediation analysis
cov_boot <- test_mediation(BSG2014,
                           x = "ValueDiversity",
                           y = "TeamCommitment",
                           m = "TaskConflict",
                           method = "covariance")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using a bootstrap test based on winsorization via a Huber M-estimator of the covariance matrix.}
<<echo=FALSE, results="asis">>=
to_latex(cov_boot)
@
\end{table}


<<include=FALSE>>=
# compute mediation analysis
reg_sobel <- test_mediation(BSG2014,
                            x = "ValueDiversity",
                            y = "TeamCommitment",
                            m = "TaskConflict",
                            test = "sobel")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using a robust Sobel test based on robust regressions via an MM-estimator.}
<<echo=FALSE, results="asis">>=
to_latex(reg_sobel)
@
\end{table}


<<include=FALSE>>=
# compute mediation analysis
cov_sobel <- test_mediation(BSG2014,
                            x = "ValueDiversity",
                            y = "TeamCommitment",
                            m = "TaskConflict",
                            test = "sobel",
                            method = "covariance")
@

\begin{table}[h!]
\caption{Results from mediation analysis for a simple mediation model, using a robust Sobel test based on winsorization via a Huber M-estimator of the covariance matrix.}
<<echo=FALSE, results="asis">>=
to_latex(cov_sobel)
@
\end{table}


% ----------
% references
% ----------

% \bibliographystyle{plainnat}
% \bibliography{bibfile}   % name the BibTeX data base

\end{document}
